org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.context-path=/hdsc

org.jobrunr.queues.default-queue-name=Default
org.jobrunr.queues.names=HighPrio, Default, LowPrio

org.jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.my-rate-limiter=3
org.jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.my-other-rate-limiter=20
org.jobrunr.jobs.dynamic-queue.round-robin.label-prefix=tenant:
org.jobrunr.jobs.dynamic-queue.round-robin.title=Tenants

org.jobrunr.background-job-server.delete-succeeded-jobs-after=2h
org.jobrunr.background-job-server.permanently-delete-deleted-jobs-after=4h

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:jobrunr;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
# the below integrates JobRunr with Spring Actuator Metrics.
# best is to only enable it on your server that has the dashboard running
org.jobrunr.jobs.metrics.enabled=true
