jobrunr.background-job-server.enabled=true
jobrunr.dashboard.enabled=true

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.a=50
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.b=15
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.c=15
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.d=40
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.e=40
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.f=1
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.g=5
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.h=1
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.i=1
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.j=3
jobrunr.jobs.rate-limiter.sliding-time-window-rate-limiter.k=3000/PT1H
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.l=10
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.m=5
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.n=10
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.o=5
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.p=1
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.q=5
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.r=10
jobrunr.jobs.rate-limiter.concurrent-job-rate-limiter.s=1
